---
name: build
on: push
jobs:
  make:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        tox:
          - py27
          - py36
          - py37
          - pre-commit
          - mypy
          - docs
          # TODO: benchmark
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: pip install tox coveralls
      - run: tox -e ${{ matrix.tox }}
